font_family JetBrainsMonoNL Nerd Font
font_size 16.0
cursor_shape block

macos_hide_from_tasks no
macos_option_as_alt yes
macos_hide_titlebar yes
macos_titlebar_color system

macos_traditional_fullscreen yes
map cmd+enter toggle_fullscreen

background_image $HOME/.config/kitty/images/gradient_background.png
background_image_layout cscaled
dynamic_background_opacity 0.1
background_tint 0.95
