font_family JetBrainsMonoNL Nerd Font
font_size 16.0

cursor_shape block
cursor_blink_interval 0

enable_audio_bell no
visual_bell_duration 0.0
visual_bell_color none
window_alert_on_bell no

remember_window_size yes
window_padding_width 0
placement_strategy top-left

macos_hide_from_tasks no
macos_option_as_alt yes
macos_hide_titlebar yes
macos_titlebar_color system

macos_traditional_fullscreen yes
map cmd+enter toggle_fullscreen

background_image $HOME/.config/kitty/images/gradient_background.png
background_image_layout cscaled
dynamic_background_opacity 0.1
background_tint 0.95
