font_family JetBrainsMonoNL Nerd Font
font_size 16.0

cursor_shape block
cursor_blink_interval 0

enable_audio_bell no
visual_bell_duration 0.0
visual_bell_color none
window_alert_on_bell no

remember_window_size yes
window_padding_width 0
placement_strategy top-left

macos_hide_from_tasks no
macos_option_as_alt yes
macos_hide_titlebar yes
macos_titlebar_color system

macos_traditional_fullscreen yes
map cmd+enter toggle_fullscreen

background_image $HOME/.config/kitty/images/gradient_background.png
background_image_layout cscaled
dynamic_background_opacity 0.1
background_tint 0.88

background #011627
foreground #bdc1c6
cursor #9ca1aa
color0 #1d3b53
color1 #fc514e
color2 #a1cd5e
color3 #e3d18a
color4 #82aaff
color5 #c792ea
color6 #7fdbca
color7 #a1aab8
color8 #7c8f8f
color9 #ff5874
color10 #21c7a8
color11 #ecc48d
color12 #82aaff
color13 #ae81ff
color14 #7fdbca
color15 #d6deeb
selection_background #b2ceee
selection_foreground #080808
