#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/lib/shared.sh"

function install_homebrew() {
  if ! command_exists "brew"; then
    echo "Installing homebrew..."

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"

    brew update
  fi
}

# ╭──────────────────────────────────────────────────────────╮
# │ Basics                                                   │
# ╰──────────────────────────────────────────────────────────╯
mkdir -p ~/.local/bin

symlink_dotfile bin/slack-thread-format.rb ~/.local/bin/slack-thread-format
symlink_dotfile bin/truecolor.sh ~/.local/bin/truecolor

# ╭──────────────────────────────────────────────────────────╮
# │ MacOS                                                    │
# ╰──────────────────────────────────────────────────────────╯
if is_macos; then
  symlink_dotfile bin/emoji-intensifies.sh ~/.local/bin/emoji-intensifies

  # ╭──────────────────────────────────────────────────────────╮
  # │ Hammerspoon                                              │
  # ╰──────────────────────────────────────────────────────────╯
  symlink_dotfile bin/daily.sh ~/.local/bin/daily
  symlink_dotfile bin/dnd-toggle.sh ~/.local/bin/dnd-toggle
  symlink_dotfile hammerspoon ~/.hammerspoon

  # ╭──────────────────────────────────────────────────────────╮
  # │ Karabiner                                                │
  # ╰──────────────────────────────────────────────────────────╯
  symlink_dotfile karabiner "$(xdg_config_dir)/karabiner"

  # ╭──────────────────────────────────────────────────────────╮
  # │ Obsidian                                                 │
  # ╰──────────────────────────────────────────────────────────╯
  if [ -d "$HOME/Documents/David" ]; then
    symlink_dotfile obsidian/obsidian.vimrc "$HOME/Documents/David/.obsidian.vimrc"
  fi
fi

# ╭──────────────────────────────────────────────────────────╮
# │ Homebrew                                                 │
# ╰──────────────────────────────────────────────────────────╯
install_homebrew
brew bundle

# ╭──────────────────────────────────────────────────────────╮
# │ tmux                                                     │
# ╰──────────────────────────────────────────────────────────╯
symlink_dotfile tmux "$(xdg_config_dir)/tmux"
symlink_dotfile tmuxinator "$(xdg_config_dir)/tmuxinator"

# ╭──────────────────────────────────────────────────────────╮
# │ ZSH                                                      │
# ╰──────────────────────────────────────────────────────────╯
symlink_dotfile zsh/inputrc ~/.inputrc
symlink_dotfile zsh/zshrc ~/.zshrc
symlink_dotfile zsh/zsh ~/.zsh

# ╭──────────────────────────────────────────────────────────╮
# │ Terminal                                                 │
# ╰──────────────────────────────────────────────────────────╯
mkdir -p "$(xdg_config_dir)/alacritty"
symlink_dotfile alacritty/alacritty.toml "$(xdg_config_dir)/alacritty/alacritty.toml"

# ╭──────────────────────────────────────────────────────────╮
# │ Git                                                      │
# ╰──────────────────────────────────────────────────────────╯
symlink_dotfile git/bin/git-churn.sh ~/.local/bin/git-churn
symlink_dotfile git/bin/git-delete-merged-branches.sh ~/.local/bin/git-delete-merged-branches
symlink_dotfile git/bin/git-local-repos.sh ~/.local/bin/git-local-repos
symlink_dotfile git/bin/git-main-branch.sh ~/.local/bin/git-main-branch
symlink_dotfile git/bin/git-submit.sh ~/.local/bin/git-submit
symlink_dotfile git/bin/git-switch-interactive.sh ~/.local/bin/git-switch-interactive
symlink_dotfile git/bin/git-what-i-did.sh ~/.local/bin/git-what-i-did

mkdir -p "$(xdg_config_dir)/git"
symlink_dotfile git/attributes "$(xdg_config_dir)/git/attributes"
symlink_dotfile git/config "$(xdg_config_dir)/git/config"
symlink_dotfile git/ignore "$(xdg_config_dir)/git/ignore"
symlink_dotfile git/message "$(xdg_config_dir)/git/message"

function git_user_config() {
  if is_stripe_machine; then
    echo "git/config.user.stripe"
  else
    echo "git/config.user.default"
  fi
}

symlink_dotfile "$(git_user_config)" "$(xdg_config_dir)/git/config.user"

# ╭──────────────────────────────────────────────────────────╮
# │ Ruby                                                     │
# ╰──────────────────────────────────────────────────────────╯
symlink_dotfile ruby/pryrc.rb ~/.pryrc

# ╭──────────────────────────────────────────────────────────╮
# │ Neovim                                                   │
# ╰──────────────────────────────────────────────────────────╯
