#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y \
  autojump \
  bat \
  direnv \
  eza \
  fzf \
  libreadline-dev \
  libreadline8t64 \
  openssl \
  ripgrep \
  tmux \
  tmuxinator \
  wget \
  xz-utils \
  zplug \
  zsh

function install_github_release() {
  local bin_name="$1"
  local url="$2"

  if [ -x "$HOME/.local/bin/$bin_name" ]; then
    echo "Skipping install of $bin_name, already exists"
    return 0
  fi

  echo "Installing $bin_name from $url"

  mkdir -p ~/.local/bin
  pushd ~/.local/bin >/dev/null || exit

  curl -L "$url" -o "$bin_name"
  chmod +x "$bin_name"

  popd >/dev/null || exit
}

# Grab the latest nvim dev version (0.11.x at time of writing)
install_github_release nvim \
  https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-arm64.appimage

install_github_release diff-so-fancy \
  https://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.4/diff-so-fancy
