#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

require_installer package-manager
# require_installer mac-app-store
# require_installer mac-custom-apps
require_installer git
require_installer devtools
require_installer zsh
require_installer python
require_installer ruby
require_installer tmux
require_installer fonts
require_installer neovim
# require_installer spacemacs
# require_installer backups
# require_installer os-keys
# require_installer audio
