#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

function install_nix() {
  if ! command_exists nix ; then
    curl --proto '=https' --tlsv1.2 -sSf \
      -L https://install.determinate.systems/nix \
      | sh -s -- install

    source_nix_shell

    sudo -i nix-channel --update nixpkgs
  else
    echo "Nix already installed, skipping"
  fi
}

function source_nix_shell() {
  if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  fi
}

function symlink_nix_config() {
  mkdir -p ~/.config
  symlink_dotfile nix/default ~/.config/nix
}

function install_home_manager() {
  if ! command_exists "home-manager" ; then
    nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update

    nix-shell '<home-manager>' -A install
  fi
}

function rebuild_nix_home() {
  home-manager build
  home-manager switch
  [ -e result ] && rm result
}

function zsh_binary() {
  echo "$HOME/.nix-profile/bin/zsh"
}

function update_shell_whitelist() {
  local zshbin=$(zsh_binary)
  if ! cat /etc/shells | grep -q "$zshbin"; then
    echo "Adding $zshbin to /etc/shells, please enter your sudo password"

    echo $zshbin | sudo tee -a /etc/shells > /dev/null
  fi
}

function chsh_zsh() {
  if [[ "$SHELL" != "$(zsh_binary)" ]]; then
    dotsay "@b@blue[[Changing shell for $current_user...]]"

    local current_user=$USER
    sudo chsh -s $(zsh_binary) $current_user
  fi
}


symlink_dotfile nix/home-manager ~/.config/home-manager
symlink_nix_config
source_nix_shell
install_nix
install_home_manager
rebuild_nix_home
update_shell_whitelist
chsh_zsh
