#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function setup_git_scripts() {
  mkdir -p ~/.local/bin

  symlink_dotfile bin/git/git-delete-merged-branches \
    ~/.local/bin/git-delete-merged-branches

  symlink_dotfile bin/git/git-local-repos ~/.local/bin/git-local-repos

  symlink_dotfile bin/git/git-what-i-did ~/.local/bin/git-what-i-did
}

dotheader "Setting up Git..."

install_package "git"

brew_tap jesseduffield/lazygit
brew_install lazygit

setup_git_scripts

symlink_dotfile bin/git-main-branch ~/.local/bin/git-main-branch
