#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer ruby
require_installer python
require_installer node

function setup_neovim_config() {
	mkdir -p ~/.config
	symlink_dotfile nvim ~/.config/nvim
}


function install_tern() {
	npm install -g tern
}

function install_vim_node_rpc() {
	npm install -g vim-node-rpc
}

function install_ruby_neovim() {
	if use_rvm; then
		rvm default do gem install neovim
	fi
}

function install_rust() {
	if ! command_exists "cargo"; then
		brew_install rustup
		rustup-init -y
		source $HOME/.cargo/env
	fi
}

function install_stylua() {
	if ! command_exists "stylua"; then
		cargo install --force stylua
	fi
}

function install_bash_language_server() {
	yarn global add bash-language-server
}

function install_lua_language_server() {
	brew_install lua-language-server
}

function install_typescript_language_server() {
	yarn global add typescript-language-server
}

function install_vscode_language_servers() {
	yarn global add vscode-langservers-extracted
}

function install_yaml_language_server() {
	yarn global add yaml-language-server
}

function install_write_good() {
	yarn global add write-good
}

function install_emmet_lsp() {
	if ! command_exists "emmet-ls"; then
		dotsay "@b@blue[[+ Installing Emmet LSP]]"
		npm install -g emmet-ls
	fi
}

dotheader "Setting up Neovim..."

install_emmet_lsp
install_lua_language_server
install_bash_language_server
install_ruby_neovim
install_typescript_language_server
install_write_good
setup_neovim_config
install_tern
install_vim_node_rpc
install_neovim_plugins
install_rust
install_stylua
install_vscode_language_servers
install_yaml_language_server
