#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer fonts
require_installer ruby
require_installer python
require_installer node

function install_neovim_linux() {
  if ! apt_is_installed "neovim"; then
    sudo add-apt-repository -y ppa:neovim-ppa/stable
    sudo apt-get -y update
    apt_install neovim

    sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
    sudo update-alternatives --config vi
    sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
    sudo update-alternatives --config vim
    sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
    sudo update-alternatives --config editor
  fi
}

function install_neovim_mac() {
  if ! brew_is_tapped "neovim/neovim"; then
    brew_tap neovim/neovim
  fi

  brew_install neovim
}

function install_neovim() {
  if is_macos; then
    install_neovim_mac
  else
    install_neovim_linux
  fi
}

function setup_neovim_config() {
  mkdir -p ~/.config
  symlink_dotfile nvim ~/.config/nvim
}

function ensure_plugin_directory() {
  mkdir -p ~/.local/share/nvim/plugged
}

function install_neovim_plugins() {
  dotsay "@b@blue[[+ Installing nvim plugins]]"
  pyenv activate py2neovim
  nvim +PlugInstall +qall
}

function install_tern() {
  npm install -g tern
}

function install_vim_node_rpc() {
  npm install -g vim-node-rpc
}

function install_ruby_neovim() {
  if use_rvm; then
    rvm default do gem install neovim
  fi
}

function install_rust() {
  if ! command_exists "cargo" ; then
    brew_install rustup
    rustup-init -y
    source $HOME/.cargo/env
  fi
}

function install_proximity_sort() {
  if ! command_exists "proximity-sort" ; then
    cargo install --force proximity-sort
  fi
}

function install_bash_language_server() {
  npm install -g bash-language-server
}

function install_bat() {
  brew_install bat

  mkdir -p ~/.config/bat
  symlink_dotfile bat/config ~/.config/bat/config
}

function install_lua_language_server() {
  brew_install ninja

  local lspdir="$HOME/.local/nvim/lsp"
  local location="$lspdir/lua-language-server"

  if [ ! -d "$location" ]; then
    dotsay "@b@blue[[+ Installing sumneko Lua LSP]]"

    mkdir -p "$lspdir"
    git clone https://github.com/sumneko/lua-language-server "$location"

    cd "$location" || exit 1
    git submodule update --init --recursive

    cd 3rd/luamake || exit 1
    ./compile/install.sh
    cd ../.. || exit 1
    ./3rd/luamake/luamake rebuild
  fi
}

function install_typescript_language_server() {
  npm install -g typescript-language-server
}

function install_emmet_lsp() {
  if ! command_exists "emmet-ls"; then
    dotsay "@b@blue[[+ Installing Emmet LSP]]"
    npm install -g emmet-ls
  fi
}

dotheader "Setting up Neovim..."

install_emmet_lsp
install_lua_language_server
install_bash_language_server
install_ruby_neovim
install_typescript_language_server
install_neovim
setup_neovim_config
install_tern
install_vim_node_rpc
ensure_plugin_directory
install_neovim_plugins
install_rust
# Broken on santa
# install_proximity_sort
install_bat
