#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# We need to hook RVM's cd function to get auto-cd with nvm
require_installer ruby

function source_nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
}

function install_nvm() {
  if [ ! -d ~/.nvm ]; then
    curl -o- \
      https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash

    source_nvm

    nvm install stable
  fi
}

function install_yarn_linux() {
  ! is_linux && return 1

  if ! command_exists "yarn"; then
    # Force Node 9.x
    sudo apt-get remove -y nodejs
    curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

    # Add yarn repository
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | \
      sudo apt-key add -

    echo "deb https://dl.yarnpkg.com/debian/ stable main" | \
      sudo tee /etc/apt/sources.list.d/yarn.list

    apt_update
    apt_install nodejs
    apt_install yarn
  fi
}

function install_after_cd_nvm_hook_to_rvm() {
  local hook_file=$HOME/.rvm/hooks/after_cd_nvm

  if [ ! -f $HOME/rvm ]; then
    echo "Installing after_cd_nvm hook to RVM..."
    symlink_dotfile zsh/hooks/rvm/after_cd_nvm "$hook_file"
  fi
}

function install_nodenv() {
  brew_install nodenv
  brew_upgrade node-build

  nodenv init
  nodenv install -s 18.10.0
  nodenv global 18.10.0
}

if use_nvm; then
  install_nvm
  source_nvm
  install_after_cd_nvm_hook_to_rvm
else
  install_nodenv
fi

brew_install yarn
install_yarn_linux
