#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

dotheader "Setting up Hammerspoon..."
brew_cask_install hammerspoon --appdir=/Applications

function setup_development_spoon_from_git_repo() {
  local name=$1
  local code_dir=$HOME/code
  local source_dir=$code_dir/$name.spoon
  local symlink_destination=$HOME/.hammerspoon/Spoons/$name.spoon

  mkdir -p "$code_dir"

  if [ ! -d $source_dir ]; then
    dotsay "@blue@b[[+ cloning development copy of $name.spoon ]]"
    git clone https://github.com/dbalatero/$name.spoon "$source_dir"
  else
    dotsay "+ $name.spoon dev copy already checked out"
  fi

  if [ ! -d $symlink_destination ]; then
    dotsay "@blue@b[[+ symlinking development copy of $name.spoon ]]"
    ln -s "$source_dir" "$symlink_destination"
  else
    dotsay "+ $name.spoon already installed to Hammerspoon"
  fi
}

function install_spoon() {
  local spoon_name=$1
  local url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/$spoon_name.spoon.zip"
  local destination=/tmp/$spoon_name.spoon.zip
  local spoons_dir=$HOME/.hammerspoon/Spoons

  mkdir -p "$spoons_dir"

  if [ ! -d "$spoons_dir/$spoon_name.spoon" ]; then
    dotsay "@blue@b[[+ installing $spoon_name.spoon ]]"

    wget -nv $url -O $destination
    unzip -d $spoons_dir $destination
  else
    dotsay "+ $spoon_name.spoon already setup"
  fi
}

function install_m1ddc() {
  local location="$HOME/.local/bin/m1ddc"

  if [ ! -f "$location" ]; then
    dotsay "@blue@b[[+ installing m1ddc ]]"

    git clone git@github.com:waydabber/m1ddc.git /tmp/m1ddc
    cd /tmp/m1ddc && make
    cp /tmp/m1ddc/m1ddc "$location"
    rm -fr /tmp/m1ddc
  fi
}

install_m1ddc
symlink_dotfile bin/dnd-toggle ~/.local/bin/dnd-toggle

# monitor switching
brew_install ddcctl

brew_install lua
brew_install luarocks

# bluetooth
brew_install blueutil

brew_cask_install karabiner-elements
symlink_dotfile karabiner ~/.config/karabiner

luarocks install loop
luarocks install dkjson
luarocks install inspect
luarocks install --server=http://luarocks.org/dev lua-lsp
luarocks install luacheck
luarocks install lcf

symlink_dotfile hammerspoon ~/.hammerspoon
install_spoon SpoonInstall
setup_development_spoon_from_git_repo HyperKey
setup_development_spoon_from_git_repo VimMode
setup_development_spoon_from_git_repo SkyRocket
