#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  if test ! $(which brew); then
    echo "Installing homebrew"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"

    brew update
  fi

  dotheader "Setting up Homebrew..."
elif is_linux; then
  dotheader "Setting up Aptitude..."

  apt_install aptitude
fi

# Apt build

buildtools=(
  make
  cmake
  build-essential
  libssl-dev
  zlib1g-dev
  libbz2-dev
  libreadline-dev
  libsqlite3-dev
  wget
  curl
  llvm
  libncurses5-dev
  xz-utils
  tk-dev
)

for package in "${buildtools[@]}"; do
  apt_install "$package"
done
