#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

is_macos && export PYTHON_CONFIGURE_OPTS="--enable-framework"
is_linux && export PYTHON_CONFIGURE_OPTS="--enable-shared"

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

function load_pyenv() {
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
}

function install_python_versions() {
  pyenv install -s 2.7.18
  pyenv install -s 3.9.1
  pyenv global 2.7.18
}

function install_pyenv_virtualenvs() {
  if ! pyenv virtualenvs | grep -q py2neovim; then
    pyenv virtualenv 2.7.18 py2neovim
    pyenv activate py2neovim
    pip install --upgrade pip
    pip install neovim
  fi

  if ! pyenv virtualenvs | grep -q py3neovim; then
    pyenv virtualenv 3.9.1 py3neovim
    pyenv activate py3neovim
    pip install --upgrade pip
    pip install neovim
  fi
}

dotheader "Setting up Python..."

brew_install readline
brew_install xz

brew_install pyenv
brew_install pyenv-virtualenv
load_pyenv

install_python_versions
install_pyenv_virtualenvs
