#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function setup_rvmrc() {
  symlink_dotfile rvmrc ~/.rvmrc
}

function install_latest_ruby() {
  rvm install ruby --latest
}

function install_global_gem_hooks() {
  local destination="$HOME/.rvm/hooks/after_install_add_default_gems"

  symlink_dotfile rvm/hooks/after_install_add_default_gems $destination
  chmod +x $destination
}

function install_rvm() {
  if [ ! -e ~/.rvm ]; then
    \curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles

    export PATH="$HOME/.rvm/bin:$PATH"
    [ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm

    install_global_gem_hooks
    install_latest_ruby
  fi
}

function setup_pry() {
  symlink_dotfile irb/pryrc ~/.pryrc
  symlink_dotfile irb/unescaped_colors.rb ~/.unescaped_colors.rb
  symlink_dotfile irb/escaped_colors.rb ~/.escaped_colors.rb
  symlink_dotfile irb/aprc ~/.aprc
}

function install_yard() {
  gem install yard
}

function bootstrap_rvm() {
  if use_rvm; then
    dotsay "@b@blue[[Installing RVM...]]"
    setup_rvmrc
    install_rvm
    install_global_gem_hooks
    install_yard
  else
    dotsay "@b@yellow[[Skipping RVM, we aren't using it]]"
  fi
}

function install_rbenv_default_gems() {
  local destination=$(rbenv root)/plugins/rbenv-default-gems

  if [ ! -d "$destination" ]; then
    dotsay "+ Installing rbenv-default-gems plugin..."

    git clone https://github.com/rbenv/rbenv-default-gems.git \
      $(rbenv root)/plugins/rbenv-default-gems
  fi

  local default_gem_file=rvm/gemsets/global.gems
  local default_gem_file_destination=$(rbenv root)/default-gems

  if [ ! -f "$default_gem_file_destination" ]; then
    echo "+ Doing one-time install of default gems"

    while read -r name; do
      gem install "$name"
    done < $default_gem_file
  fi

  symlink_dotfile $default_gem_file $(rbenv root)/default-gems
}

function install_rbenv() {
  if ! command_exists "rbenv"; then
    dotsay "@b@blue[[Installing rbenv...]]"
    brew_install rbenv
  fi
}

function bootstrap_rbenv() {
  if use_rbenv; then
    dotsay "@b@blue[[Installing rbenv extras...]]"
    install_rbenv
    install_rbenv_default_gems
  else
    dotsay "@b@yellow[[Skipping rbenv, we aren't using it]]"
  fi
}

dotheader "Setting up Ruby..."

symlink_dotfile bin/rubocop-daemon-wrapper ~/.local/bin/rubocop-daemon-wrapper
setup_pry
brew_install rubyfmt

bootstrap_rvm
bootstrap_rbenv
