#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

symlink_dotfile alacritty ~/.config/alacritty
brew_cask_install alacritty

# get fucking bent, Catalina
xattr -r -d com.apple.quarantine /Applications/Alacritty.app
