#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function install_kitty() {
  if [ ! -d "/Applications/kitty.app" ]; then
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  fi
}

function install_alacritty() {
  if [ ! -d "/Applications/Alacritty.app" ]; then
    brew_cask_install alacritty
  fi
}

symlink_dotfile kitty ~/.config/kitty
symlink_dotfile alacritty ~/.config/alacritty

install_alacritty
install_kitty

# get fucking bent, Catalina
xattr -r -d com.apple.quarantine /Applications/Alacritty.app
