#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function install_tmux_plugins() {
  local install_script="$HOME/.tmux/plugins/tpm/bin/install_plugins"

  if [ -x $install_script ]; then
    $install_script
  fi
}

function setup_tmux_config() {
  symlink_dotfile tmux.conf ~/.tmux.conf
  symlink_dotfile tmux.osx.conf ~/.tmux.osx.conf
  symlink_dotfile tmux ~/.tmux

  if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone git@github.com:tmux-plugins/tpm.git ~/.tmux/plugins/tpm
    install_tmux_plugins
  fi
}

function setup_tmux_base16_integration() {
  symlink_dotfile tmux/tmuxcolors-dbalatero-base16.conf \
    ~/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf
}

function setup_tmuxinator() {
  symlink_dotfile tmuxinator ~/.tmuxinator
}

function install_tmux_from_source_linux() {
  ! is_linux && return 1

  packages=(
    wget
    tar
    libevent-dev
    libncurses-dev
  )

  for package in "${packages[@]}"; do
    apt_install $package
  done

  if command_exists "tmux"; then
    return 0
  fi

  local version="2.4"

  wget https://github.com/tmux/tmux/releases/download/${version}/tmux-${version}.tar.gz && \
    tar xf tmux-${version}.tar.gz && \
    cd tmux-$version && \
    ./configure --prefix=/usr/local && \
    make && \
    sudo make install && \
    cd .. && \
    rm -fr tmux-${version}
}

dotheader "Setting up Tmux..."

brew_install reattach-to-user-namespace
brew_install urlview

install_tmux_from_source_linux

setup_tmux_config
setup_tmuxinator
setup_tmux_base16_integration
