#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer ruby

function zsh_binary() {
  if is_linux; then
    echo /bin/zsh
  elif is_macos; then
    echo /opt/homebrew/bin/zsh
  fi
}

function update_shell_whitelist() {
  local zshbin=$(zsh_binary)
  if ! cat /etc/shells | grep -q $zshbin; then
    echo "Adding $zshbin to /etc/shells, please enter your sudo password"

    echo $zshbin | sudo tee -a /etc/shells > /dev/null
  fi
}

function chsh_zsh() {
  if [[ "$SHELL" != "$(zsh_binary)" ]]; then
    dotsay "@b@blue[[Changing shell for $current_user...]]"

    local current_user=$USER
    sudo chsh -s $(zsh_binary) $current_user
  fi
}

function install_antigen() {
  local plugin_file=$HOME/.zsh/vendor/antigen.zsh

  if [ ! -f $plugin_file ]; then
    echo "Installing antigen"
    curl -L git.io/antigen > "$plugin_file"
  fi
}

function install_base16_shell() {
  local base16_repo=$HOME/.config/base16-shell

  if [ ! -d $base16_repo ]; then
    echo "Installing base16-shell..."
    git clone https://github.com/chriskempson/base16-shell.git "$base16_repo"
  fi

  ln -sf /Users/dbalatero/.antigen/bundles/chriskempson/base16-shell/scripts/base16-oceanicnext.sh ~/.base16_theme
}

dotheader "Setting up ZSH..."

symlink_dotfile profile ~/.profile
symlink_dotfile inputrc ~/.inputrc
symlink_dotfile zsh/starship.toml ~/.config/starship.toml

brew_install starship

install_base16_shell

install_fasd

install_antigen

update_shell_whitelist
chsh_zsh
