#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer ruby

function install_base16_shell() {
  local base16_repo=$HOME/.config/base16-shell

  if [ ! -d $base16_repo ]; then
    echo "Installing base16-shell..."
    git clone https://github.com/chriskempson/base16-shell.git "$base16_repo"
  fi

  ln -sf /Users/dbalatero/.antigen/bundles/chriskempson/base16-shell/scripts/base16-oceanicnext.sh ~/.base16_theme
}

dotheader "Setting up ZSH..."

install_base16_shell
install_package zsh-completions
