# https://coderwall.com/p/trgyrq/make-your-tmux-status-bar-responsive
SESSION_SEP=""

set -g status-position top
set -g status-interval 1
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 20
set -g status-left "#[bg=colour33,fg=colour255]   #[fg=colour33,bg=colour234]#[bg=default,fg=default,bold]#[fg=default,bg=default] #S #[fg=colour214]$SESSION_SEP "
set -g status-right "#{prefix_highlight} #(eval tmux-airline `tmux display -p '#{client_width}'`)"
set -g status-right-length 150
set -g window-status-format "#[fg=colour244,bg=colour234]#I #[fg=colour240] #[default]#W "
set -g window-status-current-format "#[fg=colour234,bg=colour33]#[fg=colour117,bg=colour33] #I  #[fg=colour231,bold]#W #[fg=colour33,bg=colour234,nobold]"
set -g window-status-style fg=colour249,none
set -g window-status-activity-style fg=yellow,none
set -g window-status-bell-style fg=red,none
